import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background) / <alpha-value>)",
        foreground: "rgb(var(--foreground) / <alpha-value>)",
        card: "rgb(var(--card) / <alpha-value>)",
        "card-foreground": "rgb(var(--card-foreground) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        "primary-foreground": "rgb(var(--primary-foreground) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        muted: "rgb(var(--muted) / <alpha-value>)",
        "muted-foreground": "rgb(var(--muted-foreground) / <alpha-value>)",
        "glass-bg": "var(--glass-bg)",
        "glass-border": "var(--glass-border)",
        
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary": "#5f5e5f",
        "surface-container-low": "#f3f4f5",
        "surface": "#f8f9fa",
        "on-primary-container": "#dad7ff",
        "on-secondary-fixed": "#1b1b1c",
        "inverse-primary": "#c3c0ff",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#636263",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e5e2e3",
        "inverse-surface": "#2e3132",
        "surface-tint": "#4d44e3",
        "tertiary-container": "#a44100",
        "on-surface": "#191c1d",
        "secondary-container": "#e2dfe0",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container": "#edeeef",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "tertiary": "#7e3000",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed-variant": "#474647",
        "on-background": "#191c1d",
        "outline-variant": "#c7c4d8",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed": "#ffdbcc",
        "surface-dim": "#d9dadb",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-container": "#ffd2be",
        "secondary-fixed-dim": "#c8c6c7",
        "surface-container-high": "#e7e8e9",
        "surface-variant": "#e1e3e4",
        "outline": "#777587",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#4f46e5",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed": "#351000",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        base: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        heading: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h1": ["36px", { lineHeight: "1.3", fontWeight: "700" }],
        "h2": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "h3": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        "subtle": "0 4px 20px rgba(0, 0, 0, 0.04)",
        "elevated": "0 8px 30px rgba(0, 0, 0, 0.06)",
        "card": "0 2px 10px rgba(0, 0, 0, 0.03)",
        "glass": "0 8px 32px 0 rgba(31, 38, 135, 0.07)",
        "glass-hover": "0 8px 32px 0 rgba(31, 38, 135, 0.15)",
        "neon": "0 0 10px rgba(79, 70, 229, 0.5), 0 0 20px rgba(79, 70, 229, 0.3)",
      },
      animation: {
        "blob": "blob 7s infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "aurora": "aurora 60s linear infinite",
        "marquee": "marquee 30s linear infinite",
      },
      keyframes: {
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(calc(-100% - 2rem))" },
        },
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        aurora: {
          from: {
            backgroundPosition: "50% 50%, 50% 50%",
          },
          to: {
            backgroundPosition: "350% 50%, 350% 50%",
          },
        },
      }
    },
  },
  plugins: [],
};
export default config;
